version: '3.7'

services:

  agent:
    image: datadog/agent:latest
    ports:
      - 8125:8125
      - 8126:8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_ENV=trace_examples_java

  java:
    image: java:8-jdk
    volumes:
      - ./:/var/trace-examples
      - gradle-cache:/root/.gradle
    working_dir: /var/trace-examples
    depends_on:
      - agent
    ports:
      - 8080:8080
    environment:
      DD_AGENT_HOST: agent
    entrypoint: ./app_start.sh
    command: "java -javaagent:dd-java-agent.jar -jar spring-app/build/libs/trace-examples-0.1.0.jar"

  locust:
    image: python:3.7
    depends_on:
      - java
    volumes:
      - ./:/var/app
    working_dir: /var/app
    command: bash
#    command: pip install -r requirements.txt
#    command: "pip install -r requirements.txt && locust -f locust-files/HomeControllerProfiling.py --no-web -c 100 -r 5"

volumes:
  gradle-cache:
